"""Logging utilities façade (M5)."""
from __future__ import annotations

from lumina_core.logging_autonomy import compute_autonomy_snapshot  # noqa: F401
from lumina_core.logging_core import (  # noqa: F401
    _CORRELATION_ID,
    _MONITORING_IO_LOCK,
    _RUNTIME_TRACE_THROTTLE_STAGES,
    _TRACE_EMIT_LOCK,
    _TRACE_LAST_EMIT_MONO,
    EVENT_CODES,
    _fmt_trace_val,
    _safe_log,
    build_logger,
    correlation_id,
    flush_logger_handlers,
    get_logger,
    log_event,
    log_runtime_trace,
    runtime_trace_enabled,
    runtime_trace_interval_sec,
    setup_logging,
)
from lumina_core.logging_evolution import (  # noqa: F401
    log_decision_flow,
    log_evolution_event,
    log_gate_rejection,
    log_shadow_verdict,
    log_twin_decision,
)
from lumina_core.logging_monitoring import (  # noqa: F401
    _append_jsonl,
    _monitoring_state_path,
    _write_json,
    classify_twin_decision_outcome,
    record_autonomy_metrics_monitoring,
    record_gate_rejection_monitoring,
    record_model_load_time_monitoring,
    record_reasoning_latency_monitoring,
    record_shadow_twin_alignment_monitoring,
    record_twin_decision_monitoring,
    record_twin_steve_accuracy_monitoring,
    record_twin_training_metrics_monitoring,
    resolve_monitoring_state_dir,
    write_ppo_policy_metadata,
    write_runtime_monitoring_snapshot,
)

__all__ = [
    "EVENT_CODES",
    "runtime_trace_enabled",
    "runtime_trace_interval_sec",
    "_fmt_trace_val",
    "log_runtime_trace",
    "log_event",
    "get_logger",
    "correlation_id",
    "_safe_log",
    "log_evolution_event",
    "log_twin_decision",
    "log_shadow_verdict",
    "log_gate_rejection",
    "log_decision_flow",
    "flush_logger_handlers",
    "build_logger",
    "setup_logging",
    "compute_autonomy_snapshot",
    "resolve_monitoring_state_dir",
    "_monitoring_state_path",
    "_append_jsonl",
    "_write_json",
    "record_twin_decision_monitoring",
    "record_twin_training_metrics_monitoring",
    "record_gate_rejection_monitoring",
    "record_model_load_time_monitoring",
    "write_ppo_policy_metadata",
    "write_runtime_monitoring_snapshot",
    "record_reasoning_latency_monitoring",
    "classify_twin_decision_outcome",
    "record_autonomy_metrics_monitoring",
    "record_twin_steve_accuracy_monitoring",
    "record_shadow_twin_alignment_monitoring",
]
