"""Trend indicator helpers for RL observation enrichment (ADR-0018)."""
from __future__ import annotations

from lumina_core.rl.trend_features_core import (  # noqa: F401
    ADX_PERIODS,
    ATR_PERIOD,
    DEFAULT_TREND_ADX_THRESHOLD,
    ENRICH_VERSION,
    MIN_TREND_LOOKBACK,
    SLOPE_PERIODS,
    _TREND_FEATURE_KEYS,
    _adx_from_tr,
    _extract_ohlc_from_ticks,
    _normalize_slope,
    _to_float_series,
    _true_range_series,
    _zero_trend_features,
    compute_adx,
    compute_atr,
    linear_regression_slope,
    regime_strength_score,
    trend_persistence,
)
from lumina_core.rl.trend_features_batch import (  # noqa: F401
    _build_trend_feature_dict,
    _numpy_adx_last,
    _numpy_ewm,
    _numpy_rolling_mean,
    _numpy_true_range,
    _precompute_slopes,
    compute_trend_features_for_window,
    compute_trend_features_from_ticks,
    compute_trend_features_sliding_batch,
    compute_trend_features_sliding_batch_reference,
    regime_from_strength,
)

__all__ = [
    "MIN_TREND_LOOKBACK",
    "DEFAULT_TREND_ADX_THRESHOLD",
    "ENRICH_VERSION",
    "SLOPE_PERIODS",
    "ADX_PERIODS",
    "ATR_PERIOD",
    "compute_atr",
    "compute_adx",
    "linear_regression_slope",
    "trend_persistence",
    "regime_strength_score",
    "compute_trend_features_for_window",
    "compute_trend_features_sliding_batch",
    "compute_trend_features_sliding_batch_reference",
    "compute_trend_features_from_ticks",
    "regime_from_strength",
]
