"""Birth curriculum stage scorecard helpers for UI transparency.

Blocker logic: ``stage_blocker.compute_stage_blocker`` (re-exported).
Criteria: ``stage_scorecard_criteria`` (re-exported).
Enrichment: ``stage_scorecard_enrich`` (re-exported).
"""

from __future__ import annotations

from typing import Any

from lumina_core.birth.config import BirthCurriculumConfig
from lumina_core.birth.curriculum import (
    CurriculumStage,
    stage_pass_trades,
)

from lumina_core.birth.stage_blocker import compute_stage_blocker  # noqa: F401
from lumina_core.birth.stage_scorecard_criteria import (  # noqa: F401
    CURRICULUM_STAGE_COUNT,
    PassCriteria,
    _pass_gate_label,
    compute_advancing,
    curriculum_index_for_stage,
    human_sub_phase,
    learning_metric_target,
    parse_curriculum_stage,
    pass_criteria_for_stage,
    runway_curriculum_total,
    stage_display_name,
)
from lumina_core.birth.stage_scorecard_enrich import (  # noqa: F401
    calculate_simple_slope,
    combined_learning_velocity,
    compute_regime_distribution,
    enrich_adaptation_payload,
    enrich_progress_scorecard,
    format_regime_distribution_summary,
)

SCORECARD_PRESERVE_KEYS: tuple[str, ...] = (
    "curriculum_stage",
    "stage_trades",
    "stage_target_trades",
    "stage_training_budget_trades",
    "stage_wins",
    "stage_winrate",
    "stage_hold_ratio",
    "stage_hold_signals",
    "stage_total_signals",
    "curriculum_index",
    "curriculum_total",
    "stage_pass_now",
    "median_loss_r",
    "mean_r",
    "occupancy",
    "edge_vs_first_touch",
    "stages_passed",
    "pass_criteria_id",
    "pass_criteria_label",
    "pass_metric_label",
    "pass_metric_target",
    "pass_metric_min",
    "pass_metric_max",
    "stage_display_name",
    "sub_phase",
    "sub_phase_label",
    "constitution_violations",
    "is_advancing",
    "patterns_mined",
    "learning_attempt",
    "birth_start_time",
    "elapsed_sec",
    "exploration_active",
    "oracle_wins",
    "escalation_level",
    "gen0_provisional",
    "data_days_loaded",
    "requested_days",
    "actual_calendar_days",
    "requested_instrument",
    "resolved_instrument",
    "rolled",
    "stitched",
    "instruments",
    "stitched_from",
    "expansion_step",
    "stage_range_hold_signals",
    "stage_range_total_signals",
    "stage_range_flat_bars",
    "stage_range_round_trips",
    "stage_range_flat_ratio",
    "occupancy_control_flat",
    "stage_wall_remaining_sec",
    "stage_blocker_metric",
    "stage_blocker_value",
    "pass_reason",
    "provisional_pass",
    "volume_gate_status",
    "winrate_trend_slope",
    "last_adaptation",
    "retries_this_stage",
    "adaptation_tier",
    "max_adaptation_tiers",
    "max_stage_retries",
    "auto_recovery_active",
    "adaptation_enabled",
    "wall_behavior",
    "learning_velocity_combined",
    "strong_recovery_mode",
    "velocity_stall_attempts",
    "strong_recovery_attempts",
    "provisional_pass_considered",
    "meta_primary_strategy",
    "meta_learning_health",
    "meta_pattern_quality",
    "meta_reward_tweak_active",
    "meta_reward_expectancy_coeff",
    "meta_review_trigger",
    "meta_explore_multiplier",
    "meta_rollouts_since_review",
    "meta_last_rationale",
    "meta_strategy_history",
    # Birth trade geometry + exit physics (must survive partial progress writes).
    "birth_trade_stop_pct",
    "birth_trade_target_pct",
    "birth_trade_geometry_source",
    "geometry_time_ordered",
    "geometry_p40_raw",
    "geometry_hold_bars",
    "geometry_pool_size",
    "geometry_macro_rejected",
    "geometry_floor_bound",
    "geometry_net_rr",
    "e_mech",
    "first_touch_p_ft",
    "foundation_schema",
    "foundation_replay_ok",
    "foundation_unique_calendar_days",
    "geometry_net_rr_after_cost",
    "geometry_breakeven_wr_after_cost",
    "geometry_cost_usd",
    "geometry_ref_price",
    "first_touch_target_hit_rate",
    "edge_vs_random",
    "geometry_econ_proxy_mismatch",
    "pass_vector_flat",
    "pass_vector_expectancy",
    "pass_vector_exp_floor",
    "pass_vector_edge_vs_random",
    "pass_vector_occupancy_over_gap",
    "pass_vector_occupancy_under_gap",
    "pass_vector_exp_gap",
    "pass_vector_edge_gap",
    "pass_vector_dominant",
    "pass_vector_action",
    "pass_vector_in_flat_band",
    "pass_vector_beat_random",
    "stage2_bootstrap_patterns",
    "stage2_bootstrap_updates",
    "stage2_action_head_reinit",
    "participation_force_exit",
    "stage1_foundation_target_wr",
    "stage1_foundation_winrate",
    "stage1_foundation_learning_gap",
    "stage1_foundation_pressure",
    "stage1_anti_thrash",
    "stage1_survival_ok",
    "stage1_edge_vs_random",
    "stage1_transfer_handoff_ok",
    "stage1_transfer_purge_mode",
    "stage1_transfer_reinit_ok",
    "stage_policy_trades",
    "stage_policy_wins",
    "stage_plant_trades",
    "stage_plant_wins",
    "skill_metric_policy_only",
    "skill_metric_eligible",
    "skill_metric_trades",
    "skill_metric_wins",
    "skill_metric_winrate",
    "skill_metric_expectancy",
    "total_metric_winrate",
    "total_metric_expectancy",
    "skill_pass_wr_floor",
    "economic_be_wr",
    "skill_wr_vs_economic_be",
    "economic_training_pressure",
    "closes_stop",
    "closes_target",
    "closes_flatten",
    "closes_time_stop",
    "closes_unknown",
    "stage_closes_stop_cum",
    "stage_closes_target_cum",
    "stage_closes_flatten_cum",
    "stage_closes_time_stop_cum",
    "stage_closes_unknown_cum",
    "stage_settlement_share",
    "stage_stop_target_ratio",
    "mean_entry_stop_pct",
    "mean_entry_target_pct",
    "expectancy_quality_step",
    "expectancy_quality_step_source",
    "expectancy_stall_detected",
    "oracle_last_stop_pct",
    "oracle_last_target_pct",
    "birth_diag_contract",
    "birth_code_fingerprint",
    "birth_runtime_pid",
    "birth_runtime_python",
    "birth_runtime_cwd",
    "birth_code_has_quality_failclosed",
    "birth_code_has_geom_enrich",
    "birth_code_has_coerce",
    "birth_code_has_geometry_time_guard",
    "birth_code_collected_at",
    "birth_code_identity_ok",
    "birth_code_identity_defects",
    "meta_self_eval_phase",
    "meta_self_eval_current_strategy",
    "meta_self_eval_committed_strategy",
    "meta_self_eval_best_velocity_delta",
    "meta_self_eval_probes_completed",
    "trade_budget_cap",
    "trade_budget_remaining",
    "trade_budget_source",
    "terminal_stall_reason",
    "evolution_phase",
    "evolution_step",
    "evolution_step_label",
    "evolution_actions_remaining",
    "evolution_actions_total",
    "evolution_actions_completed",
    "evolution_phantom_steps",
    "plateau_elapsed_sec",
    "trades_beyond_gate",
    "plateau_forced_recoveries_count",
    "plateau_best_winrate",
    "needs_attention",
    "attention_reason_code",
    "attention_summary",
    "attention_recommended_actions",
    "attention_notified_at",
    "user_initiated_stop",
    "prior_stage",
    "prior_phase",
    "policy_entropy",
    "entropy_alive",
    "edgescore",
    "expectancy_proxy",
    "starship_exploration_burst_active",
    "swarm_tournament_lift_ok",
    "swarm_tournament_at_start",
    "swarm_edgescore_lift_ok",
    "swarm_edgescore_at_start",
    "swarm_rejected_no_lift",
    "best_edgescore",
    "best_edgescore_at_trade",
    "best_edgescore_policy_path",
    "edgescore_champion_min_trades",
    "edgescore_champion_locked",
    "rolling_winrate_500",
    "rolling_winrate_source",
    "rolling_window_trades_covered",
    "hygiene_wr_floor",
    "hygiene_wr_lifetime",
    "hygiene_wr_rolling",
    "hygiene_wr_effective",
    "hygiene_wr_source",
    "rolling_wr_eligible",
    "retryable",
    "constitution_violations_session",
    "constitution_violations_cumulative",
    "oos_metrics",
    "failure_reasons",
    "remediation_attempt",
    "remediation_max",
    "data_manifest",
    "retryable",
    "certificate_ok",
    "runway_phase",
    "micro_oos_probe",
    "birth_exit_winrate",
)


def build_scorecard_payload(
    *,
    stage: CurriculumStage,
    curriculum_index: int,
    stages_passed: list[str],
    stage_trades: int,
    stage_wins: int,
    stage_hold_signals: int,
    stage_total_signals: int,
    constitution_violations: int,
    target_trades: int,
    phase: str,
    patterns_mined: int,
    learning_attempt: int,
    prev_stage_trades: int = 0,
    prev_patterns_mined: int = 0,
    snapshot_elapsed_sec: float = 0.0,
    stage_range_flat_bars: int = 0,
    stage_range_total_signals: int = 0,
    stage_range_round_trips: int = 0,
    provisional_pass: bool = False,
    cfg: BirthCurriculumConfig | None = None,
    rolling_winrate: float | None = None,
    rolling_winrate_display: float | None = None,
    rolling_wr_eligible: bool | None = None,
    policy_entropy: float | None = None,
    ppo_steps: int = 0,
    policy_trades: int | None = None,
    policy_wins: int | None = None,
    plant_trades: int | None = None,
    plant_wins: int | None = None,
    consecutive_rolling_pass_windows: int = 0,
    closes_stop: int = 0,
    closes_target: int = 0,
    closes_time_stop: int = 0,
    closes_flatten: int = 0,
    closes_unknown: int = 0,
    median_loss_r: float | None = None,
    mean_r: float | None = None,
    first_touch_hit_rate: float | None = None,
    geometry_net_rr: float | None = None,
    unique_calendar_days: int | None = None,
    pnl_series: list[float] | None = None,
    stop_pct: float | None = None,
    ref_price: float | None = None,
    oos_sharpe: float | None = None,
    oos_dd_pct: float | None = None,
    r_series: list[float] | None = None,
) -> dict[str, Any]:
    criteria = pass_criteria_for_stage(stage, cfg=cfg, target_trades=target_trades)
    trades = max(0, int(stage_trades))
    wins = max(0, int(stage_wins))
    hold_ratio = float(stage_hold_signals) / float(max(1, stage_total_signals))
    winrate = float(wins) / float(max(1, trades))
    is_advancing = compute_advancing(
        stage_trades=trades,
        patterns_mined=int(patterns_mined),
        prev_stage_trades=int(prev_stage_trades),
        prev_patterns_mined=int(prev_patterns_mined),
        elapsed_since_snapshot_sec=float(snapshot_elapsed_sec),
    )
    required = stage_pass_trades(stage, cfg) if cfg is not None else criteria.target_trades
    range_flat_ratio = float(stage_range_flat_bars) / float(max(1, stage_range_total_signals))
    from lumina_core.birth.curriculum import evaluate_stage_pass

    occupancy_for_pass = (
        None
        if stage == CurriculumStage.STAGE1_TREND
        else (range_flat_ratio if int(stage_range_total_signals) > 0 else None)
    )
    engine = evaluate_stage_pass(
        stage,
        trades=trades,
        wins=wins,
        hold_signals=int(stage_hold_signals),
        total_signals=int(stage_total_signals),
        range_hold_signals=0,
        range_total_signals=int(stage_range_total_signals),
        range_flat_bars=int(stage_range_flat_bars),
        range_round_trips=int(stage_range_round_trips),
        constitution_violations=int(constitution_violations),
        target_trades=int(required),
        cfg=cfg,
        policy_entropy=policy_entropy,
        ppo_steps=int(ppo_steps),
        policy_trades=policy_trades,
        policy_wins=policy_wins,
        plant_trades=plant_trades,
        plant_wins=plant_wins,
        consecutive_rolling_pass_windows=int(consecutive_rolling_pass_windows or 0),
        closes_stop=int(closes_stop),
        closes_target=int(closes_target),
        closes_time_stop=int(closes_time_stop),
        closes_flatten=int(closes_flatten),
        closes_unknown=int(closes_unknown),
        median_loss_r=median_loss_r,
        mean_r=mean_r,
        first_touch_hit_rate=first_touch_hit_rate,
        geometry_net_rr=geometry_net_rr,
        unique_calendar_days=unique_calendar_days,
        pnl_series=pnl_series,
        stop_pct=stop_pct,
        ref_price=ref_price,
        occupancy=occupancy_for_pass,
        oos_sharpe=oos_sharpe,
        oos_dd_pct=oos_dd_pct,
        r_series=r_series,
    )
    engine_days = int(engine.unique_calendar_days or 0)
    blocker_metric, blocker_value, pass_reason = compute_stage_blocker(
        stage,
        stage_trades=trades,
        stage_wins=wins,
        hold_ratio=hold_ratio,
        required=required,
        constitution_violations=int(constitution_violations),
        range_flat_ratio=range_flat_ratio,
        range_round_trips=int(stage_range_round_trips),
        range_total_signals=int(stage_range_total_signals),
        cfg=cfg,
        rolling_winrate=rolling_winrate,
        rolling_winrate_display=rolling_winrate_display,
        rolling_wr_eligible=rolling_wr_eligible,
        policy_entropy=policy_entropy,
        ppo_steps=int(ppo_steps),
        policy_trades=policy_trades,
        policy_wins=policy_wins,
        plant_trades=plant_trades,
        plant_wins=plant_wins,
        consecutive_rolling_pass_windows=int(consecutive_rolling_pass_windows or 0),
        closes_stop=int(closes_stop),
        closes_target=int(closes_target),
        closes_time_stop=int(closes_time_stop),
        closes_flatten=int(closes_flatten),
        closes_unknown=int(closes_unknown),
        median_loss_r=engine.median_loss_r,
        mean_r=engine.mean_r,
        first_touch_hit_rate=engine.p_ft,
        geometry_net_rr=engine.net_rr,
        unique_calendar_days=engine_days,
        oos_sharpe=engine.oos_sharpe,
        oos_dd_pct=engine.oos_dd_pct,
        pnl_series=pnl_series,
        r_series=r_series,
        stop_pct=stop_pct,
        ref_price=ref_price,
        settlement_ok=bool(engine.settlement_ok),
        settlement_share=float(engine.settlement_share),
        entropy_alive=bool(engine.entropy_alive),
    )
    payload: dict[str, Any] = {
        "stage_wins": wins,
        "stage_winrate": round(winrate, 4),
        "stage_hold_ratio": round(hold_ratio, 4),
        "curriculum_index": int(curriculum_index),
        "curriculum_total": CURRICULUM_STAGE_COUNT,
        "stages_passed": list(stages_passed),
        "pass_criteria_id": criteria.id,
        "pass_criteria_label": criteria.label,
        "pass_metric_label": criteria.metric_label,
        "pass_metric_target": criteria.metric_target,
        "pass_metric_min": criteria.metric_min,
        "pass_metric_max": criteria.metric_max,
        "stage_display_name": stage_display_name(stage),
        "sub_phase": str(phase).strip().lower(),
        "sub_phase_label": human_sub_phase(phase),
        "constitution_violations": int(constitution_violations),
        "is_advancing": bool(is_advancing),
        "stage_target_trades": int(required),
        "stage_training_budget_trades": int(criteria.training_budget_trades),
    }
    if blocker_metric:
        payload["stage_blocker_metric"] = blocker_metric
        payload["stage_blocker_value"] = blocker_value
        payload["pass_reason"] = pass_reason
    else:
        payload["stage_blocker_metric"] = None
        payload["stage_blocker_value"] = None
        payload["pass_reason"] = None
    if provisional_pass:
        payload["provisional_pass"] = True
    payload["stage_pass_now"] = bool(engine.passed)
    payload.update(dict(engine.progress_fields))
    if engine.net_rr is not None:
        payload["geometry_net_rr_after_cost"] = round(float(engine.net_rr), 4)
    return payload
